package model.pojo;
// Generated 20 Nov, 2023 8:00:51 PM by Hibernate Tools 3.6.0



/**
 * Userinfo generated by hbm2java
 */
public class Userinfo  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String address;
     private String contactno;
     private String emailaddress;

    public Userinfo() {
    }

    public Userinfo(String name, String address, String contactno, String emailaddress) {
       this.name = name;
       this.address = address;
       this.contactno = contactno;
       this.emailaddress = emailaddress;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getContactno() {
        return this.contactno;
    }
    
    public void setContactno(String contactno) {
        this.contactno = contactno;
    }
    public String getEmailaddress() {
        return this.emailaddress;
    }
    
    public void setEmailaddress(String emailaddress) {
        this.emailaddress = emailaddress;
    }




}


